### ISSUE TITLE
Error rendering in untangled-client

### ISSUE THREAD

**Issue by Pancia** [untangled-web/untangled-spec#40]
TypeError cannot read property call of null in reconcile!, when trying to `((:render st))`

Try:
- [ ] def-test-suite should def renderer without genysm, but use the suite-name.
- [ ] try js/timeout between mount & runner?

**Comment by awkay** [comment]
The error can be generated by clicking on the filters in the tool bar.

**Comment by Pancia** [comment]
Seems related to protocol support, or basically something specific to untangled-client... closing the issue here, may pick up in untangled-client later.
